---
packageExtensions:
  '@babel/preset-env@*':
    dependencies:
      '@babel/core': '*'
  '@mdx-js/react@*':
    dependencies:
      react: '*'
  '@parcel/cache@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/fs@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/package-manager@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/workers@*':
    dependencies:
      '@parcel/core': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@storybook/vue3': '*'
  '@storybook/core-client@*':
    dependencies:
      webpack: '*'
  '@storybook/core-common@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/core@*':
    dependencies:
      webpack: '*'
  '@storybook/store@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/vue3@*':
    dependencies:
      '@vue/compiler-sfc': '*'
      babel-loader: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  jscodeshift@*:
    dependencies:
      '@babel/preset-env': '*'
  stylelint-high-performance-animation@*:
    dependencies:
      postcss-value-parser: '*'
  # stylelint@*:
  #   dependencies:
  #     postcss-html@*: '*'
  # '@vue/test-utils@*':
  #   dependencies:
  #     '@vue/compiler-dom@*': '*'
  '@vue/vue3-jest@*':
    dependencies:
      '@vue/compiler-sfc': '*'
  ts-loader@*:
    dependencies:
      typescript: '*'
  vue-inbrowser-compiler-utils@*:
    dependencies:
      vue: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
yarnPath: .yarn/releases/yarn-3.2.0.cjs
