---
jobs:
  name_check:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: PR Name Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Link Dependencies
        run: yarn
      - name: Ensure Commitizen Format
        uses: JulienKode/pull-request-name-linter-action@98794a8b815ec05560813c42e55fd8d32d3fd248
  size_label:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Change Size Label
    runs-on: ubuntu-latest
    steps:
      - env:
          IGNORED: |
            .yarn
            .pnp.cjs
            .pnp.loader.mjs
            yarn.lock
        name: Apply Size Label
        uses: pascalgn/size-label-action@a4655c448bb838e8d73b81e97fd0831bb4cbda1e
name: PR Checks
'on':
  pull_request:
    types:
      - opened
      - edited
      - synchronize