---
concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref || github.ref }}
jobs:
  test:
    name: Run Production Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
    timeout-minutes: 5
name: Production Tests
'on':
  push:
    branches:
      - main