name: Production Tests

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    - main

jobs:
  test:
    name: Run Production Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
